import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";
import { Providers } from "./providers";
import {
  ClerkProvider,

} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body className={inter.className}>

        <Providers>
          <Header />
          <ClerkProvider>
            {children}
          </ClerkProvider>
          <Footer />
        </Providers>
      </body>
    </html>

  );
}
